namespace apex_service.Models
{
    public class Customer
    {
        public int id { get; set; }
        public DateTime dateCreated { get; set; }
        public DateTime dateModified { get; set; }
        public string createdBy { get; set; }
        public string createdByName { get; set; }
        public string modifiedBy { get; set; }
        public string modifiedByName { get; set; }
        public string note { get; set; }
        public string agent { get; set; }
        public string subject { get; set; }
        public string callStatus { get; set; }
        public string name { get; set; }
        public string status { get; set; }
        public string cdCampaign { get; set; }
        public string cdSegment { get; set; }
        public string nhmHanmucTang { get; set; }
        public string phone2 { get; set; }
        public DateTime ngaysinh { get; set; }
        public string tgTermowner { get; set; }
        public string cmnd { get; set; }
        public string cmndNoicap { get; set; }
        public string vung { get; set; }
        public DateTime cdObDate { get; set; }
        public string onboardLoaithe { get; set; }
        public string tgNoCard { get; set; }
        public string tgHaveInstal2022 { get; set; }
        public int tuoi { get; set; }
        public string ttkTtkichhoatDebit { get; set; }
        public string ttkCardType { get; set; }
        public string cdTd { get; set; }
        public string diachi { get; set; }
        public double tgPropensityScore2 { get; set; }
        public int stt { get; set; }
        public string tgGroupHaveInterest { get; set; }
        public double tgCreditLimit { get; set; }
        public string phone { get; set; }
        public string cdRegion { get; set; }
        public string nhmLoaithe { get; set; }
        public string onboardSanphamdadung { get; set; }
        public DateTime ttkNgaytaoekyc { get; set; }
        public string gioitinh { get; set; }
        public string ttkIssuedatetoprocessdate { get; set; }
        public DateTime nhmNgaysaoke { get; set; }
        public DateTime cmndNgaycap { get; set; }
        public string tenchinhanh { get; set; }
        public string cdCurrentAddress { get; set; }
        public string nhmHanmucHt { get; set; }
        public string cdCasa { get; set; }
        public string cdLending { get; set; }
        public string email { get; set; }
        public double tgTransactionAmount { get; set; }
        public string ttkTypeIssue { get; set; }
        public string machinhanh { get; set; }
        public double cdCreditCardLimit { get; set; }
        public string ttkTrangthailogin { get; set; }
        public DateTime onboardCussince { get; set; }
        public string tgTransactorRevolver { get; set; }
        public string onboardSpdamo { get; set; }
        public double thePropensityScore { get; set; }
        public string nhmLoaithehtCao { get; set; }
        public double theSuggestedLimit { get; set; }
        public DateTime cdConsultationtime { get; set; }
        public string cdProductsRequire { get; set; }
        public string theOldNew { get; set; }
        public string nhmHanmuc { get; set; }
        public string fieldTab { get; set; }
        public DateTime hhNgayhethan { get; set; }
        public double hhLimitCms { get; set; }
        public string hhLoaithe { get; set; }
        public string hhVnaId { get; set; }
        public DateTime cdSavedate { get; set; }
        public string source { get; set; }
        public int idImport { get; set; }
        public string error { get; set; }
        public int customerId { get; set; }
        public string fkDSG { get; set; }
        public string oTP { get; set; }
        public string maHocVien { get; set; }
        public string field67 { get; set; }
    }
}
